"""Split each paper into  content.tex  (the chapter body) leaving the standalone
main .tex intact. Reports exactly what it cut, so nothing vanishes silently."""
import re, os, sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "papers")
os.chdir(ROOT)

papers = sys.argv[1:] or sorted(d for d in os.listdir('.') if d.startswith('paper_'))

# Belongs to the STANDALONE paper only, never to a chapter. NOTE: \nocite is
# NOT dropped — paper XII has no inline \cite, so its \nocite list is the only
# thing that makes its chapter bibliography non-empty. \printbibliography IS
# dropped (the volume's \paperchapter prints the per-chapter bibliography).
DROP_LINE = re.compile(
    r'^\s*\\(tableofcontents|maketitle|thispagestyle|pagestyle|printbibliography'
    r'|bibliographystyle|bibliography|addbibresource|coverfootnote)\b'
)
BODY_MARK = re.compile(r'^\s*%.*\bBody\b', re.I)

for p in papers:
    main = f"{p}/{p}.tex"
    if not os.path.exists(main):
        print(f"!! {p}: no main file"); continue
    txt = open(main, encoding='utf-8', errors='replace').read()

    b = txt.find(r'\begin{document}')
    e = txt.rfind(r'\end{document}')
    if b < 0 or e < 0:
        print(f"!! {p}: no document env"); continue
    doc = txt[b + len(r'\begin{document}'):e]
    lines = doc.split('\n')

    # locate body start: prefer an explicit "% ... Body ..." banner, else the
    # first \section / \input{sections/s...}
    start = None
    for i, ln in enumerate(lines):
        if BODY_MARK.search(ln):
            start = i + 1
            break
    if start is None:
        for i, ln in enumerate(lines):
            if re.match(r'\s*\\(section|chapter)\s*\{', ln) or \
               re.match(r'\s*\\input\{sections', ln):
                start = i
                break
    if start is None:
        print(f"!! {p}: could not find body start — needs manual split")
        continue

    head = lines[:start]      # cover / dedication / abstract / toc  (dropped or kept?)
    body = lines[start:]

    # keep the abstract from the head, if present, as a chapter headnote
    abstract = []
    ht = '\n'.join(head)
    m = re.search(r'(\\begin\{abstract\}.*?\\end\{abstract\})', ht, re.S)
    if m:
        abstract = [m.group(1)]
    else:
        m = re.search(r'\\input\{(sections/abstract[^}]*)\}', ht)
        if m:
            abstract = [r'\begin{abstract}', f'\\input{{{m.group(1)}}}', r'\end{abstract}']

    kept, cut = [], []
    for ln in body:
        if DROP_LINE.match(ln):
            cut.append(ln.strip())
        else:
            kept.append(ln)

    out = []
    out.append(f"% content.tex — the body of {p}, as a book chapter.")
    out.append("% GENERATED by split_content.py. The standalone paper still builds from")
    out.append(f"% {p}.tex; both read this file, so they cannot drift apart.")
    out.append("")
    if abstract:
        out += abstract + ['']
    out += kept

    open(f'{p}/content.tex', 'w', encoding='utf-8').write('\n'.join(out).strip() + '\n')

    n_in = len(re.findall(r'\\input\{', '\n'.join(kept)))
    n_sec = len(re.findall(r'\\section\{', '\n'.join(kept)))
    print(f"{p:<40} body_lines={len(kept):<5} inputs={n_in:<3} sections={n_sec:<3} "
          f"abstract={'yes' if abstract else 'NO'} cut={len(cut)}")
    if cut:
        print(f"      cut: {', '.join(sorted(set(c[:28] for c in cut)))}")
