# Build this paper independently (it finds ../../serendip-paper.sty).
#   latexmk        build PDF (xelatex + biber/bibtex as needed)
#   latexmk -c     clean aux files   |   latexmk -C   also remove the PDF
$ENV{'TEXINPUTS'} = '../../:' . ($ENV{'TEXINPUTS'} // '');
$pdf_mode   = 5;     # xelatex
$bibtex_use = 2;     # run biber/bibtex when a bibliography is present
$max_repeat = 7;     # dense cross-refs; allow extra passes
@default_files = ('paper_10_joint_attention_of_value.tex');
